- name: Setup Cog
  uses: replicate/setup-cog@v0.8.6
  with:
    token: ${{ secrets.REPLICATE_API_TOKEN }}

- name: Download weights
  run: cog run script/download-weights

- name: Push to Replicate
  run: cog push r8.im/ahadalii/controlnet
