name: Push to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        required: true
        description: "rossjillian/controlnet"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Cog
        uses: replicate/setup-cog@v1.0.3
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Download weights
        run: cog run script/download-weights

      - name: Push to Replicate
        run: cog push r8.im/ahadalii/controlnet
